# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
Character.destroy_all
UserGuide.destroy_all

users = [
  {username: "Hasibul23", password_digest: "123", profile_image: "https://ca.slack-edge.com/T02MD9XTF-U01CRNE8X3M-0cc327fd8ec0-512"},
  {username: "Greg111", password_digest: "abc", profile_image: "https://ca.slack-edge.com/T02MD9XTF-U8H2RA3C1-643c8ce562ef-512"},
  {username: "Michelle45", password_digest: "456", profile_image: "https://ca.slack-edge.com/T02MD9XTF-U011WKXUXTK-5ce7733b96e2-512"}
]

users.each {|user| User.create(user)}


characters = [
    {name: "Ky Kiske",  grid_image: "https://www.guiltygear.com/ggst/en/wordpress/wp-content/uploads/2020/09/archive_kyk.jpg", description: "A serious man who dedicates himself completely to his work, the people, and his morals. His love for justice and determination to help those less fortunate is reflected in all aspects of his life. On the other hand, this also means he can show rather extreme dislike for anything that disrupts the peace or breaks the rules. After taking his position as King, this enthusiasm shifted into a broader perspective, allowing him to see the world from a variety of viewpoints. This isn't to say, however, that he can't still come off as naïve and emotional at times.", detail_image:"https://www.fightersgeneration.com/nf8/char5/ggstrive/ky-guiltygear-strive-artwork.png"},
    {name: "Sol Badguy", grid_image:"https://www.guiltygear.com/ggst/en/wordpress/wp-content/uploads/2020/09/archive.jpg" , description: "A blunt and short-tempered man. He only speaks when required, and uses as few words as he can get away with. He's not very good at explaining things, so he prefers to express himself with his aggressive behavior and attitude. While most see him as selfish and violent, those closest to him accept him for who he is.", detail_image:"https://www.fightersgeneration.com/nf8/char5/ggstrive/solbadguy-guiltygear-strive-artwork.png" },
    {name: "Ramlethal Valentine", grid_image:"https://www.guiltygear.com/ggst/en/wordpress/wp-content/uploads/2020/09/archive_ram-1.jpg", description: "She is a 'Valentine,' a life form created in the image of humanity. In accordance with the orders from her mother implanted in her memories, she declared war against humanity. However, through her interactions with Sol and everyone, she came to know emotion, and eventually became an ally to mankind.", detail_image: "https://www.fightersgeneration.com/nf9/char/ramlethal-valentine-guiltygear-strive.png"},
    {name: "Anji Mito", grid_image:"https://www.guiltygear.com/ggst/en/wordpress/wp-content/uploads/2020/12/anji.jpg", description: "Anji is one of the few that have inherited the precious Japanese blood. Because there are only a handful of Japanese in this time period, they are under government protection. Thus, they do not receive the same treatment as regular citizens. Within the Japanese community, there are those that accept this treatment, and those that reject it. Anji is part of the latter; rather than being concerned about the preservation of his race, he wants to regain his freedom as a human being. Because of this, he disguises his nationality and travels the world in pursuit of 'the man' known to have created the Gears and who is responsible for the destruction of the Japanese people. However, he pursues him not out of hatred or revenge.", detail_image: "https://www.fightersgeneration.com/news2021/char/anji-mito-guiltygear-strive-character-art.png"},
    {name: "Faust", grid_image:"https://www.guiltygear.com/ggst/en/wordpress/wp-content/uploads/2020/09/archive_fau.jpg" , description: "Faust (originally called Dr. Baldhead) was once a good man and a great surgeon; one of the best in the world. After committing a simple mistake that cost a young female patient her life, his mind broke and he went on a murderous rampage. He was captured and sent to a dimensional prison after taking the lives of scores of innocent people using the most indescribable of means.", detail_image:"https://www.fightersgeneration.com/nf9/char/faust-guiltygear-strive-artwork.png" },
    {name: "Giovanna", grid_image:"https://www.guiltygear.com/ggst/en/wordpress/wp-content/uploads/2020/09/archive_gio.jpg" , description: "Giovanna is a special operations unit officer. Her wolf spirit, named Rei, is her trusty companion. Giovanna allows her wolf spirit to possess her, giving her inhuman speed to gain the advantage over her enemies..", detail_image:"https://www.guiltygear.com/ggst/en/wordpress/wp-content/uploads/2020/09/chara_pc_gio.webp" },
    {name: "May", grid_image: "https://www.guiltygear.com/ggst/en/wordpress/wp-content/uploads/2020/09/archive_may-1.jpg", description: "Having lost her parents at a young age, she was picked up by the pirate Johnny and named May. As she lived the rough life as a chivalrous robber, she began to be charmed by Johnny's kindness and broadmindedness. Ever since, her life has become completely dedicated to Johnny. May was able to reunite with Johnny after the tournament, which filled her with happiness. One day, as Johnny's birthday was nearing, the crew decided to give him a present as a sign of their appreciation. Compelled by her growing feelings for him, she wanted to give him a gift personally, not as part of the crew. The problem was, she didn't have money. Then she learned of the huge bounty put on the Gear.", detail_image: "https://www.fightersgeneration.com/nf8/char5/ggstrive/may-guiltygear-strive-artwork.png"},
    {name: "Axl Low", grid_image: "https://www.guiltygear.com/ggst/en/wordpress/wp-content/uploads/2020/09/archive_axl.jpg", description: "Axl is a time traveler of British descent. He is actually from the twentieth century. Born in the slums, he placed himself in the middle of gang warfare to bring peace to the town, and with his extraordinary physical prowess he was able to achieve his goal, without any casualties, in six months time. Some time later, he was forced to travel 150 years in the future. Hoping to gain passage back to his time, he entered the tournament. Instead, he was sent to another time period for a year's time. During that period, he was bounced around in the time-space continuum for an equivalent of three years. Through his journey, he learned that in each time period, there were always rumors of another time traveler like him. Axl believed that by pursuing the traveler known as 'the man', he could come upon a way to go back to his time. Sensing the presence of 'the man' behind the incident with the Gear, he decides to check it out himself. Axl's design is loosely based on Axl Rose of Gun's & Roses." , detail_image: "https://www.fightersgeneration.com/nf8/char5/ggstrive/axl-guiltygear-strive-artwork.png"},
    {name: "Chip Zanuff", grid_image: "https://www.guiltygear.com/ggst/en/wordpress/wp-content/uploads/2020/09/archive_chp.jpg", description: "In his youth, Chipp was addicted to drugs and worked for the Mafia as a buyer. Eventually, his drug dependency worsened to the point where he could no longer perform his job. No longer needed by the Mafia, Chipp was to be disposed of when a ninja, who later became his teacher, rescued him. Chipp began to open up to the man who saved his life, and became his apprentice. But, that peace was short-lived. Eventually, the Mafia killed the ninja. Trembling in anger, he vowed to take revenge on the Mafia. Unable to reach the final rounds in the tournament, he learned that his heart, skills and strength were still lacking, and devoted himself even more to his training. Upon seeing Justice's death, he realized that even the monster that massacred countless people was searching for help. This made him think about what a true helping hand was. It was then that he heard of a Gear that was not a threat to mankind.", detail_image: "https://www.fightersgeneration.com/nf8/char5/ggstrive/chipp-guiltygear-strive-artwork.png"},
    {name: "Nagoriyuki", grid_image: "https://www.guiltygear.com/ggst/en/wordpress/wp-content/uploads/2020/09/archive_nag.jpg", description: "Nagoriyuki is described as a noble vampire samurai who wields a bloodsucking blade. He wears a white mechanical mask which resembles a Japanese hannya mask and fights with two katana. The name Nagoriyuki is Japanese for 'lingering snow,'' a sentimental phrase referring to out of season snowfall during the spring. Nagoriyuki's name is likely an homage to the famous 1975 folk song 'Nagori Yuki' by IRUKA, originally performed by the band Kaguya Hime in 1974.", detail_image: "https://www.fightersgeneration.com/news2020/char/nagoriyuki-guiltygear-strive-artwork-transparent.png"},
    {name:"Leo Whitefang", grid_image: "https://www.guiltygear.com/ggst/en/wordpress/wp-content/uploads/2020/09/archive_leo.jpg", description:"Leo is one of the three Allied Kings of the Allied Kingdom of Illyria. He shared a friendly rivalry with Ky Kiske, whom he was once good friends with during the Crusade Era. His battle capabilities and leadership are said to be so outstanding that, one time, while facing the dangers of being annihilated in the battlefront, he managed to lead his unit back to safety. Due to his disorderly way of speaking, he might seem like an open-hearted man, but he's actually rather conservative. He has a high self-esteem and hates losing, and he's also a hard worker who always gives it his all." , detail_image: "https://www.fightersgeneration.com/news2020/char/leo-whitefang-ggstrive-art-transparent.png"},
    {name:"Zato-1" , grid_image: "https://www.guiltygear.com/ggst/en/wordpress/wp-content/uploads/2020/09/archive_zat.jpg", description:"Zato is the leader of an organization of assassins, who gained the ability to manipulate shadows in exchange for his vision. Originally a lowly assassin, he gained new power through a forbidden ritual, which allowed him to rise to his present position. The repeated battles of the last tournament took their toll on him, and the shadow seized control of his body. The shadow was cognizant that it was created as a weapon and that its intentions of murder and destruction were only programmed instincts. It had developed the will of its own; the ability to break away from its cursed fate. This newborn soul could not understand humans, and was filled with loneliness. While in search for others like it, the shadow comes across the rumor of the Gear. He is named after the blind swordsman Zatoichi, which is how Zato-1 would be said in Japanese." , detail_image: "https://www.guiltygear.com/ggst/en/wordpress/wp-content/uploads/2020/09/chara_pc_zat.webp"},
    {name:"Potemkin" , grid_image: "https://www.guiltygear.com/ggst/en/wordpress/wp-content/uploads/2020/09/archive_pot.jpg", description:"Potemkin is a former slave soldier of Zepp, a militaristic nation that maintains a society based on science and technology. Having taken the rest of the slave soldiers hostage, he was sentenced by his superior to enter the tournament. During the tournament, he learned that a coup d'etat was in progress. In the end, the coup d'etat succeeded and Zepp was freed from its dictatorship. President Gabriel, Potemkin's former instructor, summoned him for a secret mission; to protect a Gear from the bounty hunters and bring it back safely to Zepp. Though Potemkin is unable to discern the mission's true motive, he decides to trust his former master, and accepts the mission." , detail_image: "https://www.fightersgeneration.com/nf8/char5/ggstrive/potemkin-guiltygear-strive-artwork.png"},
    {name: "I-No", grid_image: "https://www.guiltygear.com/ggst/en/wordpress/wp-content/uploads/2021/02/rxx82us.jpg", description: "A mysterious woman whose identity is unknown, I-No talks to men with words of temptations that no man can resist, and laughs in her heart as she enjoys watching their reactions. I-No will poke her face into anything or anywhere she has interest in. During the time of Guilty Gear XX, I-No manipulates many characters against one other, and hands out fake bounty lists to Jam and Bridget. She is supposedly based off of Ringo Shiina, a popular Japanese musician who sings in the group Tokyo Jihen", detail_image: "https://www.fightersgeneration.com/news2021/char/ino-guiltygear-strive-character-art.png"},
    {name:"Millia Rage" , grid_image: "https://www.guiltygear.com/ggst/en/wordpress/wp-content/uploads/2020/09/archive_mll.jpg", description:"Losing both of her parents when she was still a child, Millia was trained by a group of assassins to use her hair as weapon. Her conscience would not allow her to murder innocent people, and as the result, she left the organization. Being pursued by the assassins, she decided that it was more efficient to put an end to the organization than to run away from it. She entered the tournament to kill Zato, the leader of the organization. Her plan was technically a success and she did gain her freedom, but her feelings - the guilt of causing her former master to be overtaken by the shadow and the fear of having to confront him again - still troubled her. Finally, out of her agony came a conclusion: I must finish him off." , detail_image: "https://www.guiltygear.com/ggst/en/wordpress/wp-content/uploads/2020/09/chara_pc_mll.webp"}
  ]

characters.each {|character| Character.create(character)}


userguides = [
  {character_id: 1, user_id: 1, title: "Hasibul Guide", content: "jhasrjhaskhdkashdkjahsdkjhasdkjhasjkdhaskjdasjkhdajshdkjahsdkjhaskjdhakjshdkjahsdkjhajksdh", guide_image: "https://ca.slack-edge.com/T02MD9XTF-U01CRNE8X3M-0cc327fd8ec0-512", likes: 0},
  {character_id: 3, user_id: 1, title: "Greg Guide", content: "abc.jbv s.kdjv/sjdvb/skjvb/sJBF'euwi weu'ew[;,LDJHyudoerpguergpuergpwugpg,lfywefup   efwp    ewgiuwefgiufjshdvlshdvldS", guide_image: "https://ca.slack-edge.com/T02MD9XTF-U8H2RA3C1-643c8ce562ef-512", likes: 0},
  {character_id: 2, user_id: 3,title: "Michelle Guide", content: "456sdjahskdjhaksjdhakjshdkjahskdjhaskjdhkajshdkjahsdjkhaskjdhkashdkjahsdkjashdkjhaksdhjakjshdajkahskdha", guide_image: "https://ca.slack-edge.com/T02MD9XTF-U011WKXUXTK-5ce7733b96e2-512", likes:0}
]

userguides.each {|guide| UserGuide.create(guide)}



puts "SEEDED 🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱"